# Generated by Django 4.2.4 on 2023-08-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_messages', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
